language: cpp

compiler:
  - gcc
  - clang

cache:
  - apt
  - ccache

sudo: false

addons:
  apt:
    packages:
      - libdb-dev
      - libreadline-dev
      - libssl-dev
      - libwww-perl
      - xsltproc
      - zlib1g-dev
      - libboost-dev

before_script:
  - ccache -s
  - ./bootstrap
  - ./configure CC="ccache $CC" CXX="ccache $CXX"
  - grep CXX config.status
  - make

env:
  - TEST_TARGET=debug
  - TEST_TARGET=release

script:
  - ./runtest.pl ALL $TEST_TARGET
  - ccache -s
