language: cpp
branches:
  only:
    - master
compiler:
  - gcc
  - clang
cache: apt
sudo: false
addons:
  apt:
    packages:
      - libdb-dev
      - libreadline-dev
      - libssl-dev
      - libwww-perl
      - xsltproc
      - zlib1g-dev
script: ./bootstrap && ./configure && make && ./runtest.pl ALL debug && ./runtest.pl ALL release

