language: cpp

compiler:
  - gcc
  - clang

cache:
  - apt
  - ccache

sudo: false

addons:
  apt:
    # We need cmake > 2.8.7
    # https://github.com/travis-ci/travis-ci/issues/4631#issuecomment-191153634
    sources:
      - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
    packages:
      - cmake
      - cmake-data
      - libdb-dev
      - libreadline-dev
      - libssl-dev
      - libwww-perl
      - xsltproc
      - zlib1g-dev

env:
  - TEST_TARGET=debug
  - TEST_TARGET=release
  - BUILD=cmake TEST_TARGET=debug
  - BUILD=cmake TEST_TARGET=release

script:
  - ./infrastructure/travis-build.sh
