language: cpp

branches:
  only:
    - master

compiler:
  - gcc
  - clang

cache:
  - apt
  - ccache

sudo: false

addons:
  apt:
    packages:
      - libdb-dev
      - libreadline-dev
      - libssl-dev
      - libwww-perl
      - xsltproc
      - zlib1g-dev

before_cache: ccache -s

before_script:
  - ./bootstrap
  - ./configure CC='ccache clang -Qunused-arguments -fcolor-diagnostics' CXX='ccache clang -Qunused-arguments -fcolor-diagnostics'
  - make

script:
  - ./runtest.pl ALL debug
  - ./runtest.pl ALL release

after_cache: ccache -s
