language: cpp

compiler:
  - gcc
  - clang

cache: apt

sudo: false

addons:
  apt:
    packages:
      - libdb-dev
      - libreadline-dev
      - libssl-dev
      - libwww-perl
      - xsltproc
      - zlib1g-dev

before_script: 
  - ./bootstrap 
  - ./configure 
  - make 

env:
  - TEST_TARGET=debug
  - TEST_TARGET=release

script: 
  - ./runtest.pl ALL $TEST_TARGET

