language: cpp

branches:
  only:
    - master

compiler:
  - gcc
  - clang

cache:
  - apt
  - ccache

sudo: false

addons:
  apt:
    packages:
      - libdb-dev
      - libreadline-dev
      - libssl-dev
      - libwww-perl
      - xsltproc
      - zlib1g-dev

before_script:
  - ccache -s
  - ./bootstrap
  - ./configure CC="ccache $CC" CXX="ccache $CXX"
  - grep CXX config.status
  - make

script:
  - ./runtest.pl ALL debug
  - ./runtest.pl ALL release
  - ccache -s
