language: cpp

compiler:
  - gcc
  - clang

cache:
  - apt
  - ccache

sudo: false

addons:
  apt:
    packages:
      - cmake
      - libdb-dev
      - libreadline-dev
      - libssl-dev
      - libwww-perl
      - xsltproc
      - zlib1g-dev

env:
  - TEST_TARGET=debug
  - TEST_TARGET=release
  - BUILD=cmake

script:
  - ./infrastructure/travis-build.sh
