version: 1.0.{build}-{branch}

clone_depth: 1

# Do not build on tags (GitHub only)
skip_tags: true

os: Windows Server 2012

platform:
# - x86
# - x64
  - Win32

configuration:
  - Debug
  - Release

environment:
  VisualStudioVersion: 10.0
  Generator: Visual Studio 10
  OPENSSL_VERSION: 1.0.2e

cache:
  - "%APPVEYOR_BUILD_FOLDER%\\..\\zlib-1.2.8"
  - "%APPVEYOR_BUILD_FOLDER%\\..\\zlib-%PLATFORM%"
  - "%APPVEYOR_BUILD_FOLDER%\\..\\openssl-%OPENSSL_VERSION%"
  - "%APPVEYOR_BUILD_FOLDER%\\..\\openssl-%PLATFORM%"
  - "%APPVEYOR_BUILD_FOLDER%\\..\\pcre-8.38"
  - "%APPVEYOR_BUILD_FOLDER%\\..\\pcre-%PLATFORM%"
  - "%APPVEYOR_BUILD_FOLDER%\\infrastructure\\cmake\\%PLATFORM%"
  - "%APPVEYOR_BUILD_FOLDER%\\infrastructure\\cmake\\*.dir"
  
init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

build:
  parallel: true
  project: infrastructure/cmake/BoxBackup.sln

install:
  - cinst strawberryperl 7zip.commandline cmake

  - dir "C:\Program Files\Microsoft SDKs\Windows"
  - dir "C:\Program Files\Microsoft SDKs\Windows\v7.1"
  - dir "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin"
  - '"C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x86'

  - echo %PATH%
  - mkdir foo
  - rmdir /s/q foo
  - mkdir foo
  - c:\perl\bin\perl -e "print system('rmdir /s/q foo')"
  - c:\perl\bin\perl -v

  - ps: "[Net.ServicePointManager]::SecurityProtocol = 'Tls12'"

  - cd %APPVEYOR_BUILD_FOLDER%\..
  - ps: Start-FileDownload 'http://zlib.net/zlib128.zip'
  - 7za x zlib128.zip
  - cd zlib-1.2.8
  - cmake -G "%Generator%" -A %PLATFORM% -DCMAKE_INSTALL_PREFIX="..\zlib-%PLATFORM%" .
  - msbuild INSTALL.vcxproj /m /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

  - cd %APPVEYOR_BUILD_FOLDER%\..
  - ps: Start-FileDownload "https://www.openssl.org/source/openssl-$($env:OPENSSL_VERSION).tar.gz"
  - 7za x openssl-%OPENSSL_VERSION%.tar.gz
  - 7za x openssl-%OPENSSL_VERSION%.tar
  - cd openssl-%OPENSSL_VERSION%
  - perl Configure debug-VC-WIN32 no-asm --prefix="%APPVEYOR_BUILD_FOLDER%\..\openssl-%PLATFORM%"
  - ms\do_ms
  - nmake /s /f ms\nt.mak
  - nmake /s /f ms\nt.mak install

  - cd %APPVEYOR_BUILD_FOLDER%\..
  - ps: Start-FileDownload 'ftp://ftp.csx.cam.ac.uk/pub/software/programming/pcre/pcre-8.38.zip'
  - 7za x pcre-8.38.zip
  - cd %APPVEYOR_BUILD_FOLDER%\..
  - cd pcre-8.38
  - cmake -G "%Generator%" -A %PLATFORM% -DCMAKE_INSTALL_PREFIX="..\pcre-%PLATFORM%" .
  - dir
  - msbuild INSTALL.vcxproj /m /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - cd %APPVEYOR_BUILD_FOLDER%\..
  - dir
  - dir pcre-%PLATFORM%
  - dir pcre-%PLATFORM%\bin
  - dir pcre-%PLATFORM%\lib

  - cd %APPVEYOR_BUILD_FOLDER%
  - cd infrastructure\cmake
  - cmake -G "%Generator%" -A %PLATFORM%
  - cd %APPVEYOR_BUILD_FOLDER%

  - echo %PATH%
  - mkdir foo
  - rmdir /s/q foo

  - dir %APPVEYOR_BUILD_FOLDER%\..\zlib-1.2.8
  - dir %APPVEYOR_BUILD_FOLDER%\..\zlib-%PLATFORM%
  - dir %APPVEYOR_BUILD_FOLDER%\..\openssl-%OPENSSL_VERSION%
  - dir %APPVEYOR_BUILD_FOLDER%\..\openssl-%PLATFORM%
  - dir %APPVEYOR_BUILD_FOLDER%\..\pcre-8.38
  - dir %APPVEYOR_BUILD_FOLDER%\..\pcre-%PLATFORM%
  - dir %APPVEYOR_BUILD_FOLDER%\infrastructure\cmake\%PLATFORM%
  - dir %APPVEYOR_BUILD_FOLDER%\infrastructure\cmake\*.dir

test_script:
  - cd %APPVEYOR_BUILD_FOLDER%\infrastructure\cmake
  - ctest -C %CONFIGURATION% -V

