version: 1.0.{build}-{branch}

clone_depth: 1

# Do not build on tags (GitHub only)
skip_tags: true

os: Windows Server 2012

platform:
# - x86
# - x64
  - Win32

configuration:
  - Debug
  - Release

environment:
  VisualStudioVersion: 10.0
  Generator: Visual Studio 10

cache:
  - '%APPVEYOR_BUILD_FOLDER%\..\openssl-1.0.2d'
  - '%APPVEYOR_BUILD_FOLDER%\..\openssl-%PLATFORM%'
  - '%APPVEYOR_BUILD_FOLDER%\..\pcre-8.38'
  - '%APPVEYOR_BUILD_FOLDER%\..\pcre-%PLATFORM%'
  - '%APPVEYOR_BUILD_FOLDER%\%PLATFORM%'

build:
  parallel: true
  project: infrastructure/cmake/BoxBackup.sln

install:
  - cinst strawberryperl
  - cinst 7zip.commandline
  - cinst cmake

  - dir "C:\Program Files\Microsoft SDKs\Windows"
  - dir "C:\Program Files\Microsoft SDKs\Windows\v7.1"
  - dir "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin"
  - '"C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x86'
  - ps: "[Net.ServicePointManager]::SecurityProtocol = 'Tls12'"

  - cd %APPVEYOR_BUILD_FOLDER%\..
  - ps: Start-FileDownload 'http://zlib.net/zlib128.zip'
  - 7za x zlib128.zip
  - cd zlib-1.2.8
  - cmake -G "%Generator%" -A %PLATFORM% -DCMAKE_INSTALL_PREFIX="..\zlib-%PLATFORM%" .
  - msbuild INSTALL.vcxproj /m /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

  - cd %APPVEYOR_BUILD_FOLDER%\..
  - ps: Start-FileDownload 'https://www.openssl.org/source/openssl-1.0.2d.tar.gz'
  - 7za x openssl-1.0.2d.tar.gz
  - 7za x openssl-1.0.2d.tar
  - cd openssl-1.0.2d
  - perl Configure debug-VC-WIN32 no-asm --prefix=%APPVEYOR_BUILD_FOLDER%\..\openssl-%PLATFORM%
  - ms\do_ms
  - nmake /s /f ms\nt.mak
  - nmake /s /f ms\nt.mak install

  - cd %APPVEYOR_BUILD_FOLDER%\..
  - ps: Start-FileDownload 'ftp://ftp.csx.cam.ac.uk/pub/software/programming/pcre/pcre-8.38.zip'
  - 7za x pcre-8.38.zip
  - cd %APPVEYOR_BUILD_FOLDER%\..
  - cd pcre-8.38
  - cmake -G "%Generator%" -A %PLATFORM% -DCMAKE_INSTALL_PREFIX="..\pcre-%PLATFORM%" .
  - dir
  - msbuild INSTALL.vcxproj /m /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - cd %APPVEYOR_BUILD_FOLDER%\..
  - dir
  - dir pcre-%PLATFORM%
  - dir pcre-%PLATFORM%\bin
  - dir pcre-%PLATFORM%\lib

  - cd %APPVEYOR_BUILD_FOLDER%
  - dir
  - cd infrastructure\cmake
  - cmake -G "%Generator%" -A %PLATFORM% -DCMAKE_INSTALL_PREFIX="..\pcre-%PLATFORM%" .
  - dir
  - cd %APPVEYOR_BUILD_FOLDER%

test_script:
  - perl runtest.pl

