version: 1.0.{build}-{branch}

clone_depth: 1

# Do not build on tags (GitHub only)
skip_tags: true

os: Windows Server 2012

platform:
# - x86
# - x64
  - Win32

configuration:
  - Debug
  - Release

environment:
  VisualStudioVersion: 10.0
  Generator: Visual Studio 10
  OPENSSL_VERSION: 1.0.2h
  PCRE_VERSION: 8.38

cache:
  - '..\zlib-1.2.8'
  - '..\zlib-%PLATFORM%'
  - '..\openssl-%OPENSSL_VERSION%.tar.gz'
  - '..\openssl-%OPENSSL_VERSION%'
  - '..\openssl-%PLATFORM%'
  - '..\pcre-%PCRE_VERSION%.zip'
  - '..\pcre-%PCRE_VERSION%'
  - '..\pcre-%PLATFORM%'
  - 'infrastructure\cmake\build'

init:
# Uncomment the following two lines to enable RDP access to the virtual machine for debugging.
# - reg add "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp" /v UserAuthentication /t REG_DWORD /d 0 /f
# - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
# Enable HTTP proxy (http://www.appveyor.com/docs/how-to/http-proxy):
- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-http-proxy.ps1'))

build:
  parallel: true
  project: "%APPVEYOR_BUILD_FOLDER%\\..\\cmake\\BoxBackup_Windows.sln"
  verbosity: quiet

install:
  # Install cmake.portable instead of cmake, to get it on the path again:
  # http://disq.us/p/xdknrt
  - cinst --limit-output 7zip.commandline cmake.portable
  # We don't need strawberryperl on AppVeyor because there is already a Perl in c:\Perl.
  # If you are doing this on a fresh box for development, you would probably want to
  # install Chocolatey and then run:
  # cinst -y cmake strawberryperl git vim visualstudio2012express

  - '"C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x86'
  - cd %APPVEYOR_BUILD_FOLDER%\..
  - if not exist cmake md cmake
  - cd cmake
  - cmake %APPVEYOR_BUILD_FOLDER%\infrastructure\cmake\windows

  # Leave the current directory in the correct place to find the solution file using its relative path above.

test_script:
  - cd %APPVEYOR_BUILD_FOLDER%\..\cmake\boxbackup-build
  # - dir
  # - dir bin_bbackupd.dir
  # - dir %PLATFORM%
  # - dir %PLATFORM%\%CONFIGURATION%
  - ctest -C %CONFIGURATION% -V

deploy:
  release: boxbackup-$(appveyor_build_version)
  description: 'Box Backup Win32 build by AppVeyor'
  provider: GitHub
  auth_token:
    secure: Kh3Y3eadH4tC1JY5truhH5XKm218poCweaSLjxgTZ270jnvrc00tElKwnLLbuB01
  artifact: release/bin/bbackupd/bbackupd.exe
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
    configuration: release
    # appveyor_repo_tag: true        # deploy on tag push only
