version: 1.0.{build}-{branch}

clone_depth: 1

# Do not build on tags (GitHub only)
skip_tags: true

os: Windows Server 2012

platform:
# - x86
# - x64
  - Win32

configuration:
  - Debug
  - Release

environment:
  VisualStudioVersion: 10.0

build:
  parallel: true
  project: infrastructure/msvc/2010/boxbackup.sln

install:
  - cinst strawberryperl
  - cinst 7zip.commandline
  - dir "C:\Program Files\Microsoft SDKs\Windows"
  - dir "C:\Program Files\Microsoft SDKs\Windows\v7.1"
  - dir "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin"
  - '"C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64'
  - cd %APPVEYOR_BUILD_FOLDER%\..
  - ps: "[Net.ServicePointManager]::SecurityProtocol = 'Tls12'"
  - ps: Start-FileDownload 'https://www.openssl.org/source/openssl-1.0.2d.tar.gz'
  - 7za x openssl-1.0.2d.tar.gz
  - 7za x openssl-1.0.2d.tar
  - cd openssl-1.0.2d
  - perl Configure debug-VC-WIN32 no-asm --prefix=%APPVEYOR_BUILD_FOLDER%\..\openssl
  - ms\do_ms
  - nmake /c /f ms\nt.mak
  - nmake /c /f ms\nt.mak install
  - cd %APPVEYOR_BUILD_FOLDER%\..
  - ps: Start-FileDownload 'http://zlib.net/zlib128-dll.zip'
  - mkdir %APPVEYOR_BUILD_FOLDER%\..\zlib
  - cd %APPVEYOR_BUILD_FOLDER%\..\zlib
  - 7za x %APPVEYOR_BUILD_FOLDER%\..\zlib128-dll.zip
  - cd %APPVEYOR_BUILD_FOLDER%\..
  - cinst cmake
  - ps: Start-FileDownload 'ftp://ftp.csx.cam.ac.uk/pub/software/programming/pcre/pcre-8.38.zip'
  - 7za x pcre-8.38.zip
  - cd %APPVEYOR_BUILD_FOLDER%\..\pcre-8.38
  - rename pcre-8.38 pcre
  - cmake pcre
  - cd %APPVEYOR_BUILD_FOLDER%
  - dir

test_script:
  - perl runtest.pl

