version: 1.0.{build}-{branch}

clone_depth: 1

# Do not build on tags (GitHub only)
skip_tags: true

os: Windows Server 2012

platform:
# - x86
# - x64
  - Win32

configuration:
  - Debug
  - Release

environment:
  VisualStudioVersion: 10.0
  Generator: Visual Studio 10
  OPENSSL_VERSION: 1.0.2f
  PCRE_VERSION: 8.38

init:
# Uncomment the following two lines to enable RDP access to the virtual machine for debugging.
# - reg add "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp" /v UserAuthentication /t REG_DWORD /d 0 /f
# - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

build:
  parallel: true
  project: ..\cmake\BoxBackup_Windows.sln
# verbosity: quiet

install:
  # test_bbackupd needs 7zip (or cmake -E tar) to extract tar archives on Windows:
  - cinst -y --limit-output 7zip.commandline
  - dir "c:\Program Files"
  - dir "c:\Program Files (x86)"
  # We don't need strawberryperl on AppVeyor because there is already a Perl in c:\Perl.
  # If you are doing this on a fresh box for development, you would probably want to
  # install Chocolatey and then run:
  # cinst -y cmake.portable strawberryperl git vim visualstudio2012wdx
  # We install cmake.portable instead of cmake, to get it on the path again
  # <http://disq.us/p/xdknrt>.

  - '"C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x86'
  - cd %APPVEYOR_BUILD_FOLDER%\..
  - if not exist cmake md cmake
  - cd cmake
  # We need to specify the generator here, in case the user has more than one installed.
  # CMake always seems to default to the latest version of Visual Studio, not the one on
  # the current PATH.
  - cmake -G "%Generator%" -A %PLATFORM% %APPVEYOR_BUILD_FOLDER%\infrastructure\cmake\windows -DDEBUG=1

  # Leave the current directory in the correct place to find the solution file using its relative path above.

test_script:
  - cd %APPVEYOR_BUILD_FOLDER%\..\cmake\src\boxbackup-build
  # - dir
  # - dir bin_bbackupd.dir
  # - dir %PLATFORM%
  # - dir %PLATFORM%\%CONFIGURATION%
  - ctest -C %CONFIGURATION% -V --interactive-debug-mode 0

